export const ROUTE_CONSTANTS = {
  HOME: "/",
  CHANGE_PASSWORD: "/change-password",
  REGISTRATION: "/registration",
  LOGIN: "/login",
  VERIFICATION: "/verification",
  // USER: "/:userID/user",
  USER: "/user",
  USER_EDIT: "/user/:userID/edit",
  COURSE: "/courses",
  USER_COURSES: "/user/courses",
  CREATE_COURSE: "/create-course/new",
  COURSE_SYLLABUS: "/create-course/:courseID/syllabus",
  CREATE_COURSE_EDIT: "/create-course/:courseID/edit",
};
